baseurl = "https://rockandroh.netlify.app/"
languageCode = "en-us"
title = "Rock 'n' Roh"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5
[[menu.main]]
    name = "Teaching & 과외"
    url = "/teaching/"
    weight = 6
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 7
[[menu.main]]
    name = "Medium"
    url = "https://corr-roh.medium.com/"
    weight = 10

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Roh](/) 2020 | [Github](https://github.com/rockandroh) | [Medium](https://corr-roh.medium.com/)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
