---
title: \[AP Micro\] Price Elasticity
author: 
date: '2020-12-21'
slug: price-elasticity
categories:
  - Economics
tags: []
---
This page is about the economics term "Price Elasticity". 

> Setting the right price for your product or service is hard. In fact, determining price is one of the toughest things a marketer has to do, in large part because it has such a big impact on the company’s bottom line. One of the critical elements of pricing is understanding what economists call "price elasticity" - HBR

By definition, price elasticity of demand refers to the number calculated by the following formula $$ \epsilon=\frac{\Delta Q/Q}{\Delta P/P}=\frac{\partial Q}{\partial P}\cdot\frac{P}{Q}$$ which is a percentage change in quantity demanded divided by a percentage change in price.

Consumers are sensitive to the price change. More specifically, consumers are relatively less or more sensitive to price change of certain procduct(i.e., face mask) than the other. During the 2020, face mask was undoubtedly the most essential item to have so that people were willing to buy it even with ridiculously high price.

Suppose that mask company raised the price of one of its mask from 1$\$$ to 5$\$$. Then the percentage increase of price is $\frac{4}{1}$ or 400%. Now let's say the increase caused a decrease in the quantity sold from 5 million to 4 million. The percentage decrease in demand is $\frac{-1}{5}$ or -20%.  

Then by the formula, we get a price elasticity of demand: $$\frac{-0.2}{4}$$ which is -0.05. 

> Note that the negative is traditionally ignored and the absolute value of the number is used to interpret the price elasticity metric, as it’s the magnitude of distance from zero that matters.

Higher the absolute value of the number, the more sensitive customers are to price changes. And we categorize the degree of elasticity into 5 as follows:

- Perfectly elastic
  - $|\epsilon| = \infty$
  - Products that fall in this category are mostly pure commodities, says Avery. There’s no brand, no product differentiation, and customers have no meaningful attachment to the product.
- Relatively elastic
  - $|\epsilon| > 1$
- Unit elastic
  - $|\epsilon| = 1$
- Relatively inelastic
  - $|\epsilon| < 1$
  - product's with stronger brands (i.e., Apple and Porche) tend to be more inelastic, which makes building brand equity a good investment, says Avery.
- Perfectly inelastic
  - $|\epsilon| = 0$
  - We tend to see this only in cases where a firm has a monopoly on the demand. Even if I change my price, you still have to buy from me, explains Avery.
  
> Marketers should know where their products fall on this spectrum, but the actual number is less important than knowing which zone your product falls within and what will happen to consumer demand if you change your price, she says.

From the marketers' perspective, their goal is to move his or her products from relatively elastic to relatively inelastic. When, through branding or other marketing initiatives, a company increases consumers' desire for the product and their willingness to pay regardless of price, it is improving the comppany' standing compared with competitors.

However, in evaluating the effectiveness of marketing, we should not look at it in isolation. This is simply because the elasticity is also get affected by the type of product, the income of target consumers, the health of the economy, and what competitors are doing.

> As you may have figured out, this is a number that you can only calculate for certain after you've made an actual price change and seen the resulting impact on demand. And to be truly certain, you'd have to change your price multiple times to see what would happen at each price point. This is not what companies tend to do in practice. Rather, they send out questionnaires, run focus groups, or perform small-scale experiments in certain markets, to give them a sense of what would happen if they changed their price.

Such changing price practice is more doable in the case of 'Uber surge pricing' where you can find details [here](http://economicsforlife.ca/wp-content/uploads/2015/10/effects_of_ubers_surge_pricing.pdf). Or we can test several different pricing and how it brings different responses from the customers through online market rather than offline market. Alternatively, we can conduct a in-market A/B test with having two different prices.

Difficulties of using elasticity in real market scenario

- Rarely have companies tested extreme price changes. More likely, a company has a small sample of consumer responses to certain price changes, such as what happens when price is raised or lowered by 5-20%
- What consumers have historically been willing to pay for a particular product is not necessarily what they are willing to pay today or tomorrow. The challenge is that what people say they will do is not what they actually do when they are standing at the shelf
- Elasticity can often be an inexact calculation. It is impossible to know what customers will do at every price point or in the marketplace. 


